Fixes "undefined method 'protect_search_attrs'" for some PredicateBuilder#build calls.
This can sometimes occur for ArelTables that are constructed to
represent association/join records:

```
NoMethodError:
       undefined method `protect_search_attrs' for nil:NilClass
     # .../protect/lib/protect/model/predicate_builder.rb:9:in `build'
     # ./spec/models/promotion_spec.rb:66:in `block (4 levels) in <top (required)>'
```

They don't have an associated ActiveRecord subclass/model, so
`table.send(:klass)` returns nil.